In [2]:
import numpy as np

In [3]:
list = [1, 2, 10]  ; print(list * 3)

[1, 2, 10, 1, 2, 10, 1, 2, 10]


In [4]:
type(list) 

list

In [5]:
arr = np.array(list) ; print(arr * 3)

[ 3  6 30]


In [6]:
type(arr)

numpy.ndarray

In [7]:
data = [ [1,2,3], [4,5,6], [7,8,9] ]
print(data)
print(len(data))  
type(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3


list

In [8]:
arr = np.array(data)
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [9]:
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
data > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
data[data > 5] = 22
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [22, 22, 22],
       [22, 22, 22]])

# 판다스

In [12]:
import pandas as pd

In [13]:
dic = {'city': ['서울', '부산', '대전', '대구', '광주'],
        'year': [2017, 2017, 2018, 2018, 2018],
        'temp': [18, 20, 19, 21, 20]}
data = pd.DataFrame(dic) ; data

city  year  temp
0   서울  2017    18
1   부산  2017    20
2   대전  2018    19
3   대구  2018    21
4   광주  2018    20

In [14]:
data.index = ['a','b','c','d','e'] ; data

city  year  temp
a   서울  2017    18
b   부산  2017    20
c   대전  2018    19
d   대구  2018    21
e   광주  2018    20

In [15]:
data.columns = ['도시','연도','날씨'] ; data

도시    연도  날씨
a  서울  2017  18
b  부산  2017  20
c  대전  2018  19
d  대구  2018  21
e  광주  2018  20

In [16]:
data.연도

a    2017
b    2017
c    2018
d    2018
e    2018
Name: 연도, dtype: int64

In [17]:
data['연도']

a    2017
b    2017
c    2018
d    2018
e    2018
Name: 연도, dtype: int64

In [18]:
data.set_index(['도시'])

연도  날씨
도시          
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

In [19]:
data

도시    연도  날씨
a  서울  2017  18
b  부산  2017  20
c  대전  2018  19
d  대구  2018  21
e  광주  2018  20

In [20]:
data.set_index(['도시'], inplace=True)
data

연도  날씨
도시          
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

# 주석
### 주석3